# Generated by Django 5.2.5 on 2025-10-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='WhatsApp number (e.g., +91 9876543210)', max_length=15, unique=True)),
                ('name', models.CharField(blank=True, help_text='Customer name (optional)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='website', help_text='Where the subscription came from', max_length=100)),
            ],
            options={
                'verbose_name': 'WhatsApp Subscription',
                'verbose_name_plural': 'WhatsApp Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.DeleteModel(
            name='NewsletterSubscription',
        ),
    ]
